### PR TITLE
Updates to work with openMSE package structure

### PR DESCRIPTION
**Pull request by seananderson**
As Quang mentioned, we may want to rename the package: gfmse? We should probably add Quang to authors too. Thanks so much for taking this on @quang-huynh !

### CODE REVIEW

**Comment by seananderson** [comment]
I've made a bunch of changes locally, but haven't pushed yet. 

@quang-huynh , one thing I'm stuck on is `plot_historical_ts()`. It uses `object@TSdata` and used to access the "Catch" element. That no longer exists. What is the equivalent? It looks like "Removals" used to be an option too? Second question: both "Removals" and "Landings" now seem to have an additional dimension returned. What is this dimension and should it be summed over?

```r
library(MSEtool)
library(dplyr)
object <- runMSE(om, Hist = TRUE)

names(object@TSdata)
# [1] "Number"               "Biomass"              "VBiomass"             "SBiomass"            
# [5] "Removals"             "Landings"             "Discards"             "Find"                
# [9] "RecDev"               "Unfished_Equilibrium"

x <- object@TSdata[["Removals"]] %>%
   reshape2::melt() %>%
   dplyr::transmute(
     sample_id = Var1, year = Var2 + min(all_years) - 1,
     value = value, type = "Simulated"
)

dplyr::filter(x, sample_id == 1, year == 1996)
# sample_id year     value      type
# 1         1 1996  256.0888 Simulated
# 2         1 1996 2217.5599 Simulated
```

**Comment by seananderson** [comment]
Update: I've pushed my local changes in this branch: https://github.com/pbs-assess/gfdlm/tree/quang-huynh-master

Sorry, I meant to push to this pull request fork/branch, but seem to have messed that up.

**Comment by quang-huynh** [comment]
@seananderson Probably want to use Removals which is should be the sum of discards and landings. It is an array of dimension nsim x nyear x areas so just sum over the third dimension.

**Comment by seananderson** [comment]
Thanks. Got it.

@quang-huynh, there used to be elements `Ind` and `AddInd` in `object@Misc$Data`, where `object` is of class `MSE`. Where would I find those now?

```r
slotNames(object)
 [1] "Name"     "nyears"   "proyears" "nMPs"     "MPs"      "nsim"     "OM"       "Obs"      "SB_SBMSY"
[10] "F_FMSY"   "N"        "B"        "SSB"      "VB"       "FM"       "SPR"      "Catch"    "Removals"
[19] "Effort"   "TAC"      "TAE"      "BioEco"   "RefPoint" "CB_hist"  "FM_hist"  "SSB_hist" "Hist"    
[28] "PPD"      "Misc" 
```

```r
object@Misc
$extended
list()
```

**Comment by quang-huynh** [comment]
They'd be in `object@PPD[[i]]@AddInd` for the i-th MP

**Pull request merged**
